@uri = http://localhost:3001/admin/api/rest

###
GET {{uri}}/category

###
POST {{uri}}/category
Content-Type: application/json

{
  "name": "武器",
}

###
PUT {{uri}}/category/5e3c13a0b71c31ce57be5387

content-type: application/json

{
  "name": "武器2",
}

# curl -X POST -H "Content-Type: application/json" -d '{"name": "武器"}' http://localhost:3001/admin/api/category/5e3c13a0b71c31ce57be5387

###
DELETE  {{uri}}/category/5e3c13395367fcce1cb77acb
